import { useState, useEffect } from 'react';
import { Alert, Title, Text, TextInput, Flex } from '@mantine/core';
import { IconAlertCircle, IconSearch } from '@tabler/icons-react';
import { LeadGrid } from '../components/LeadGrid.component';

export function Home() {
  const [allPosts, setAllPosts] = useState<any>(null);
  const [searchText, setSearchText] = useState('');

  useEffect(() => {
    const fetchPosts = async () => {
      try {
        const response = await fetch('https://aimage.herokuapp.com/api/v1/post', {
          method: 'GET',
          headers: { 'Content-Type': 'application/json' },
        });
        if (response.ok) {
          const result = await response.json();
          setAllPosts(result.data.reverse());
        }
      } catch (error: any) {
        <Alert icon={<IconAlertCircle size="1rem" />} title="Bummer!" color="red">
          {error}
        </Alert>;
      }
    };
    fetchPosts();
  }, []);

  return (
    <div>
      <Flex direction="column" align="center">
        <Title order={1} align="center" color="teal.3">
          Community Collection
        </Title>
        <Text style={{ marginTop: '10px' }} align="center">
          Check out images generated by the community!
        </Text>
        <TextInput
          value={searchText}
          onChange={(e) => {
            setSearchText(e.target.value);
          }}
          mt={10}
          icon={<IconSearch size="0.8rem" />}
        />
      </Flex>
      {searchText ? (
        <LeadGrid
          data={allPosts?.filter(
            (item: { name: string; prompt: string }) =>
              item.name.toLowerCase().includes(searchText.toLowerCase()) ||
              item.prompt.toLowerCase().includes(searchText.toLowerCase())
          )}
        />
      ) : (
        <LeadGrid data={allPosts} />
      )}
    </div>
  );
}
